CREATE TABLE SALESORDER
     (
      STATE VARCHAR2(15)  CHECK(STATE IN('ONTARIO','SASKATCHEWAN','QUEBEC')),
      CITY VARCHAR(10) CHECK(CITY IN('TORONTO','SASKATOON','MONTREAL','OTTAWA','REGINA')),
      SNAME VARCHAR2(3) CHECK(SNAME IN('AAA','BBB','CCC')),
      AMT NUMBER(10,2) CHECK(AMT BETWEEN 10000 AND 30000),
      COMM NUMBER(10,2)
     );

INSERT INTO SALESORDER VALUES('ONTARIO','TORONTO','AAA',10000,0);
INSERT INTO SALESORDER VALUES('ONTARIO','TORONTO','AAA',10000,0);
INSERT INTO SALESORDER VALUES('ONTARIO','TORONTO','AAA',10000,0);
INSERT INTO SALESORDER VALUES('ONTARIO','TORONTO','AAA',10000,0);

INSERT INTO SALESORDER VALUES('SASKATCHEWAN','SASKATOON','AAA',20000,0);
INSERT INTO SALESORDER VALUES('SASKATCHEWAN','SASKATOON','AAA',20000,0);
INSERT INTO SALESORDER VALUES('SASKATCHEWAN','SASKATOON','AAA',20000,0);
INSERT INTO SALESORDER VALUES('SASKATCHEWAN','SASKATOON','AAA',20000,0);

INSERT INTO SALESORDER VALUES('QUEBEC','MONTREAL','AAA',30000,0);
INSERT INTO SALESORDER VALUES('QUEBEC','MONTREAL','AAA',30000,0);
INSERT INTO SALESORDER VALUES('QUEBEC','MONTREAL','AAA',30000,0);
INSERT INTO SALESORDER VALUES('QUEBEC','MONTREAL','AAA',30000,0);

INSERT INTO SALESORDER VALUES('ONTARIO','TORONTO','BBB',10000,0);
INSERT INTO SALESORDER VALUES('ONTARIO','TORONTO','BBB',10000,0);
INSERT INTO SALESORDER VALUES('ONTARIO','TORONTO','BBB',10000,0);
INSERT INTO SALESORDER VALUES('ONTARIO','TORONTO','BBB',10000,0);

INSERT INTO SALESORDER VALUES('SASKATCHEWAN','SASKATOON','BBB',20000,0);
INSERT INTO SALESORDER VALUES('SASKATCHEWAN','SASKATOON','BBB',20000,0);
INSERT INTO SALESORDER VALUES('SASKATCHEWAN','SASKATOON','BBB',20000,0);
INSERT INTO SALESORDER VALUES('SASKATCHEWAN','SASKATOON','BBB',20000,0);

INSERT INTO SALESORDER VALUES('QUEBEC','MONTREAL','BBB',30000,0);
INSERT INTO SALESORDER VALUES('QUEBEC','MONTREAL','BBB',30000,0);
INSERT INTO SALESORDER VALUES('QUEBEC','MONTREAL','BBB',30000,0);
INSERT INTO SALESORDER VALUES('QUEBEC','MONTREAL','BBB',30000,0);

INSERT INTO SALESORDER VALUES('ONTARIO','TORONTO','CCC',10000,0);
INSERT INTO SALESORDER VALUES('ONTARIO','TORONTO','CCC',10000,0);
INSERT INTO SALESORDER VALUES('ONTARIO','TORONTO','CCC',10000,0);
INSERT INTO SALESORDER VALUES('ONTARIO','TORONTO','CCC',10000,0);

INSERT INTO SALESORDER VALUES('QUEBEC','OTTAWA','CCC',20000,0);
INSERT INTO SALESORDER VALUES('QUEBEC','OTTAWA','CCC',20000,0);
INSERT INTO SALESORDER VALUES('QUEBEC','OTTAWA','CCC',20000,0);
INSERT INTO SALESORDER VALUES('QUEBEC','OTTAWA','CCC',20000,0);

INSERT INTO SALESORDER VALUES('SASKATCHEWAN','REGINA','CCC',30000,0);
INSERT INTO SALESORDER VALUES('SASKATCHEWAN','REGINA','CCC',30000,0);
INSERT INTO SALESORDER VALUES('SASKATCHEWAN','REGINA','CCC',30000,0);
INSERT INTO SALESORDER VALUES('SASKATCHEWAN','REGINA','CCC',30000,0);

UPDATE SALESORDER SET COMM=AMT*0.10 ;
